[package]
name = "SignLoginTest"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10"
hex = "0.4"